- name: configuring interfaces for l3mpls
  junos_command:
     commands:
       - set vlan-id {{unit}}
         # when: {{tag}} == 'yes'
       - set family inet address {{ipv4}}
       - set family inet6 address {{ipv6}}
         # when: {{ipv6}}
       - set description {{description}}
       - show | compare
       - commit and-quit comment "configured l3mpls interface for {{description}}"


- name: configuring routing instance
  junos_command:
     commands:
       - configure private
       - edit routing-instances {{vrf_name}}
       - set instance-type vrf
       - set interface {{interface}}.{{unit}}
       - set route-distinguisher {{rd}}
       - set vrf-target target:{{rd}}
       - set vrf-table-label
       - top
       - show | compare
       - commit and-quit comment "configured vrf for {{vrf_name}}"
  