- name: configuring interfaces for l2circuit
  junos_command:
     commands:
       - configure private
       - edit interface {{interface}}.{{unit}}
       - set vlan-id {{unit}}
         # when: {{tag}} == 'yes'
       - set encapsulation vlan-ccc
         # when: {{tag}} == 'yes'
       - set family ccc
       - set description {{description}}
       - top
       - show | compare
       - commit and-quit comment "configured ccc interface for {{description}}"

- name: configuring protocol l2circuit
  junos_command:
     commands:
       - configure private
       - edit protocol l2circuit interface {{interface}}.{{unit}}
       - set neighbor {{neighbor}}
       - set virtual-circuit-id {{unit}}
       - set mtu {{MTU}}
       - set description {{description}}
       - top
       - show | compare
       - commit and-quit comment "configured l2circuit for {{description}}"