---
#interface properties
interfaces:
  - interface: "physical_interface_name"
    description: "put_description_here"
    vlan: "put_vlan_here"
    ipv4: "put_ipv4_here"
    ipv6: "put_ipv6_here"

  # uncomment below for more interfaces
  # - interface: "put_physical_interface_name"
  #   description: "put_description_here"
  #   vlan: "put_vlan_here"
  #   ipv4: "put_ipv4_here"
  #   ipv6: "put_ipv6_here"

#static routes
routes:
  - route: "191.1.1.0/24" #put route here example 192.168.10.0/24
    next_hop: "1.1.1.1" #put nexthop here

  - route: "192.0.0.0/24" #put route here example 192.168.10.0/24
    next_hop: "discard" #put nexthop here
  # uncomment below to add more static routes
  # - route: "" #put route here example 192.168.10.0/24
  #  next_hop: "" #put nexthop here


#dynamic protocols properties
protocols:
  bgp:
    group_name: "group_name_here"
    export_policy_name: "policy_name_here"
    neighbor: "neighbor_ip_here"
    remote_as: "remote_as_here"
  when: protocol == "bgp"

  ospf:
    area_id: "area_id_here"
  when: protocol == "ospf"

  rip:
    group_name: "group_name_her"
    export_policy_name: "policy_name_here"
  when: protocol == "rip"