---
- hosts: router01
  gather_facts: no
  connection: network_cli

  tasks:
   - name: run show version on remote devices
     ios_command:
       commands: show version
     ignore_errors: yes

   - name: run show version and check to see if output contains IOS
     ios_command:
      commands: show version
      wait_for: result[0] contains IOS
     register: show_01
     ignore_errors: yes
   
   - name: show version
     debug: msg={{show_01.stdout}}

   - name: run multiple commands on remote nodes
     ios_command:
      commands:
        - show version
        - show interfaces
     ignore_errors: yes
     register: show_02

   - name: show version and interfaces
     debug: msg={{show_02.stdout}}

   - name: run multiple commands and evaluate the output
     ios_command:
      commands:
        - show version
        - show interfaces
      wait_for:
        - result[0] contains IOS
        - result[1] contains Loopback0
     ignore_errors: yes

   - name: run commands that require answering a prompt
     ios_command:
      commands:
        - command: 'clear counters GigabitEthernet0/1'
          prompt: 'Clear "show interface" counters on this interface \[confirm\]'
          answer: 'y'
        - command: 'clear counters GigabitEthernet0/2'
          prompt: '[confirm]'
          answer: "\r"
     ignore_errors: yes
