---

- hosts: 192.168.56.36 # put edge router ip here  without quote marks
  gather_facts: no
  connection: network_cli
  vars: 
     service: "internet" # internet or l3mpls or l2mpls
     protocol: "bgp" # static ospf rip bgp

  roles:
    - service provisioning

# after this edit the main.yml file in the var folder for the role chosen above
# this is for adding the service related parameters