---

- hosts: virttan
  gather_facts: no
  connection: network_cli
  vars:
     hostname: pe-router-1
     ntp_server: 10.8.8.8
     ntp_key: 123
     snmp_community: public
     interface: em3
     unit: 555
     ipv4: 172.16.0.1/30
     ipv6: 2001:2345::1/126
     description: "backhaul configured by ansible"
     as_number: 64512
     router_id: 10.1.1.1
     loopback_ip: 10.1.1.1
     igp: isis
     ibgp: yes
     static_default_route: no
     mpls: ldp 

  pre_tasks:
    - name: set bgp properties
      set_fact:
        bgp_group: iBGP
        bgp_neighbor: 10.2.2.2
      when: ibgp == yes

    - name: set isis properties
      set_fact:
          isis_net: "49.0000.0000.0000.0001.00"
      when: igp == isis

  roles:
    - edge router deployment
