---

# this play book provides a method of backing up configuration of junos devices
# the backup file is written to the `backup' folder in the playbook directory
# or role root directory, if playbook is part of an ansible role

 - hosts: 192.168.56.36
   gather_facts: no

   tasks:

      - name: backup junos configuration
        connection: local # netconf must be enabled on remote device
        junos_config:
           backup: yes
        register: config

