---

- name: configuring hostname
  junos_command:
     commands:
       - configure private
       - edit system
       - set host-name "{{hostname}}"
       - top
       - commit and-quit comment "configured hostname"

- name: configuring ntp
  junos_command:
     commands:
       - configure private
       - edit system
       - set ntp server {{ntp_server}}
       - set ntp source-address {{loopback_ip}}
       - set ntp authentication-key 1 type md5 value {{ntp_key}}
       - top
       - commit and-quit comment "configured ntp"       

- name: configuring snmp
  junos_command:
     commands:
       - configure private
       - edit snmp
       - set community {{snmp_community}}
       - set interface lo0
       - top
       - commit and-quit comment "configured snmp"

- name: configuring ssh
  junos_command:
     commands:
       - configure private
       - edit system services
       - set ssh
       - top
       - commit and-quit comment "configured ssh"

- name: configuring telnet
  junos_command:
     commands:
       - configure private
       - edit system services
       - set telnet
       - top
       - commit and-quit comment "configured telnet"

- name: configuring netconf
  junos_command:
     commands:
       - configure private
       - edit system services
       - set netconf ssh
       - top
       - commit and-quit comment "configured netconf"