---

# this ansible play shows different methods of configuring junos devices

 - hosts: 192.168.56.36
   gather_facts: no

   tasks:
      # using junos_config ansible module
      - name: configuring router interface via junos_config
        connection: local #can use "local" or "netconf" if netconf is enabled on remote device
        junos_config:
           lines: #each command must begin with set
              - set interfaces em3.999 description "configured by ansible"
              - set interfaces em3.999 vlan-id 999
              - set interfaces em3.999 family inet address 10.10.20.1/30
              - set interfaces em3.999 family inet policer input 2Mbps output 2Mbps
           comment: configured by ansible junos_config
        register: config

      - name: print the results
        debug: msg={{config}}  #junos_config module does not return the output from the cli


      # using junos_command ansible module
      - name: configuring router interface via junos_command
        connection: network_cli
        # this module is not idempotent thus will not trigger the changed flag
        junos_command:
           commands:
               - configure private
               - rollback 1  # to revert the configuration done by above junos_config module
               - commit
               - edit interface em3.999
               - set description "configured by ansible"
               - set vlan-id 999
               - set family inet address 10.10.20.1/30
               - set family inet policer input 2Mbps output 2Mbps
               - top
               - show | compare
               - commit and-quit comment "configured by ansible junos_command"
               - ping rapid 10.10.20.1 
               - "quit"
        register: config
        when: config.changed == true

        # this task will only be done if the "configuring router interface via junos_config" task changes configuration
        # this is to avoid rolling back configuration not done by that task
        # since this "configuring router interface via junos_command" task will first rollback before proceeding
        # hence the use of when conditional to check if the change flag is true from the former task


      - name: print the results
        debug: msg={{config}}
